### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by aviraldg** [jerith/xpathlet#1]
Hey, @jerith 

I'm looking at using this in an open source project. Would you consider adding a license; preferably a GPLv2-compatible one?

**Comment by jerith** [comment]
Whoops, I usually remember to do that when I start a new project. Thanks!

I'm not sure I can recommend using xpathlet in its current form for solving real problems:
- It doesn't have a `setup.py` or any other way to easily install it.
- It's missing a bunch of features, mostly around namespaces and float formatting.
- It fails at least one conformance test in a way that I've been unable to debug.

I don't currently have time to work on those things, but I'd be happy to look at pull requests if you want to do the work. :-)
